baseurl      = "https://yusufhegazy.github.io/"
title        = "My Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Subtitle for home
  homeSubtitle = "Computer Junkie and an Infosec Enthusiast"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "dark"

    [[params.social]]
        name = "twitter"
        url  = "https://twitter.com/TheHegazy"

    [[params.social]]
        name = "github"
        url  = "https://github.com/YusufHegazy/"

    [[params.social]]
        name = "linkedin"
        url  = "https://www.linkedin.com/in/yusufhegazy/"

    [[params.social]]
        name = "email"
        url  = "mailto:me@yusufhegazy.com"

    [[params.social]]
        name = "youtube"
        url  = "https://www.youtube.com/channel/UC2WSs0NTQl1UKvB6KpMVHlA"




[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Yusuf Hegazy"
    subtitle = "blog"
    keywords = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "$ cd /home/"
      logoCursorColor = "#7df5ab"
      logoCursorAnimate  = "1.2s"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
